[project]
name = "engdan77"
version = "2025.7.1"
description = "My personal profile"
requires-python = ">=3.11"
dependencies = [
    "count-code-lines",
    "jinja2>=3.1.6",
]

[tool.uv.sources]
count-code-lines = { git = "https://github.com/engdan77/count_code_lines.git" }
